In [22]:
# Import Dependencies
import pandas as pd
from pathlib import Path

In [23]:
# Create a path to the csv and read it into a Pandas DataFrame
csv_path = Path('./Resources/movie_scores.csv')
movies_df = pd.read_csv(csv_path)
movies_df.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.2,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.4,...,2.55,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5

In [24]:
# Figure out the minimum and maximum IMDB user vote count
print(movies_df["IMDB_user_vote_count"].min())
print(movies_df["IMDB_user_vote_count"].max())

243
334164

In [25]:
# Create bins in which to place values based upon IMDB vote count
bins = [0, 2500, 5000, 10000, 20000, 30000, 50000, 100000, 350000]
bins = [int(b) for b in bins] # convert the list of strings to a list of integers
# Create labels for these bins
group_labels = ['0 to 2.4k', '2.5k to 4.9k', '5k to 9k', '10k to 14k', '15k to 19k', '20k to 29k', '30k to 49k', '50k to 99k']

In [26]:
# Slice the data and place it into bins
movies_df["IMDB_user_vote_count"] = pd.cut(movies_df["IMDB_user_vote_count"], bins, labels=group_labels)

In [29]:
# Place the data series into a new column inside of the DataFrame
movies_df.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,50k to 99k,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,30k to 49k,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,3.90,4.0,4.5,3.0,4.0,4.0,627,50k to 99k,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.2,...,2.70,1.0,4.0,1.0,2.5,2.5,31,2.5k to 4.9k,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.4,...,2.55,0.5,1.5,1.5,1.5,2.5,88,10k to 14k,1021,0.5

In [31]:
# Create a GroupBy object based upon "IMDB User Votes Group"
movies_group = movies_df.groupby("IMDB_user_vote_count")


# Find how many rows fall into each bin
print(movies_group["IMDB_user_vote_count"].count())


# Create bins in which to place values based upon IMDB vote count
bins = [0, 2500, 5000, 10000, 20000, 30000, 50000, 100000, 350000]

# Create labels for these bins
group_labels = ['0 to 2.4k', '2.5k to 4.9k', '5k to 9k', '10k to 14k', '15k to 19k', '20k to 29k', '30k to 49k', '50k to 99k']

# Slice the data and place it into bins
movies_df["IMDB_user_vote_count"] = pd.cut(movies_df["IMDB_user_vote_count"], bins, labels=group_labels)

IMDB_user_vote_count
0 to 2.4k       18
2.5k to 4.9k    12
5k to 9k        16
10k to 14k      33
15k to 19k      16
20k to 29k      19
30k to 49k      16
50k to 99k      16
Name: IMDB_user_vote_count, dtype: int64

ValueError: Unable to parse string "50k to 99k" at position 0